### ISSUE TITLE
Get token failed! Unauthorized

### ISSUE THREAD

**Issue by movibeast** [beetcb/ms-graph-cli#3]
Hello,
I have tried using the app quite a few times and it always returns "Get token failed! Unauthorized" to me.
I have already given all of the permission to the app.

Please tell me what is wrong
Thanks

**Comment by beetcb** [comment]
Please show me what you have entered（Screenshots or text）

Thanks!
@movibeast

**Comment by movibeast** [comment]
https://pastebin.com/rBMqRH9t
To view, please use this pass -> QzFCQ0ZEKb
I have added it here

after you read, the data will be deleted. I have added everything so you can check. I think I have done everything correctly

**Comment by beetcb** [comment]
Wait a minute, do I need access to the API to view it? Looks like I need to login to their website to view the actual data 😂 : 

![image](https://user-images.githubusercontent.com/63141491/118672702-06ac6d00-b82b-11eb-9125-878e4a097abd.png)

**Comment by movibeast** [comment]
Now it will work @beetcb

**Comment by beetcb** [comment]
Got it.

**Comment by beetcb** [comment]
is this url match the `redirect_url` in your azure?

```text
https://heymind.github.io/tools/microsoft-graph-api-auth
```

Your account has a captcha protection mechanism, I can't log in at the moment

**Comment by movibeast** [comment]
![image](https://user-images.githubusercontent.com/34957562/118674640-947e5d00-b817-11eb-96f6-7613178236d4.png)
Yes, I have added it. I thought that it maybe because "/" at the end so I added 2 links but still it didn't work.
Regarding captcha, I can send you code.

**Comment by beetcb** [comment]
Also, make sure you fill in the redirect address in your `browser's address bar` in this step.

![image](https://user-images.githubusercontent.com/63141491/118675091-eaa9cb00-b82c-11eb-8155-661782d38756.png)

Something looks like:
```text
https://x.x/?code=xxxxxxxxxxxxxxxxxxx
```

**Comment by movibeast** [comment]
Yes, I have done that. But it says authorization failed

**Comment by movibeast** [comment]
![image](https://user-images.githubusercontent.com/34957562/118676414-03a88100-b819-11eb-9138-0018a7321673.png)
![image](https://user-images.githubusercontent.com/34957562/118676499-1622ba80-b819-11eb-91e4-f217d9c2459d.png)
![image](https://user-images.githubusercontent.com/34957562/118676579-263a9a00-b819-11eb-8634-975cef9e9fa4.png)

Please see these images

**Comment by beetcb** [comment]
Looks valid, well then, looks like we have to log in and check.
BTW, how do I skip this step?

![image](https://user-images.githubusercontent.com/63141491/118677049-825be900-b82e-11eb-9fc1-72651c6e49f8.png)

**Comment by movibeast** [comment]
Please use this RDP to access, I will login here
https://pastebin.com/fPB8ipkq

**Comment by movibeast** [comment]
Just a min, I will login

**Comment by movibeast** [comment]
Added the authenticator in RDP, it is chrome extension. Please use that. @beetcb

**Comment by beetcb** [comment]
Is it okay now? @movibeast

**Comment by movibeast** [comment]
Yes @beetcb it is good now. 
please use it

**Comment by beetcb** [comment]
> Added the authenticator in RDP, it is chrome extension. Please use that. @beetcb

You mean using chrome remotedesktop extention?

**Comment by movibeast** [comment]
Nah, once you login to rdp like you did. You can see the Authenticator added there :)

**Comment by beetcb** [comment]
Cross-origin token redemption is permitted only for the 'Single-Page Application'  @movibeast

**Comment by movibeast** [comment]
oh so I needed to selected that instead of web application? Can you change it for me because I think I may mess up

**Comment by beetcb** [comment]
1. The client_secret you previously provided is invalid. I created a new one 
2. Cross-origin token redemption is permitted only for the 'Single-Page Application' -> this is the real error

**Comment by movibeast** [comment]
Thank you very much for the help! 
Can you tell me how I can fix second issue?
{Cross-origin token redemption is permitted only for the 'Single-Page Application' -> this is the real error}

**Comment by beetcb** [comment]
Nope! This may actually be a bug from Microsoft. See this issue here [onedrive-cf-index](https://github.com/spencerwooo/onedrive-cf-index/issues/13)

My CLI basicly did the solution in that issue, should fix it, but failed in your case

**Comment by beetcb** [comment]
> oh so I needed to selected that instead of web application? Can you change it for me because I think I may mess up

Nope! This may actually be a bug from Microsoft. See this issue here onedrive-cf-index

My CLI basicly did the solution in that issue, should fix it, but failed in your case

**Comment by movibeast** [comment]
ding, so there is no solution at a moment for me?

**Comment by beetcb** [comment]
Try using the CLI again with my newly generated client_secret 

Should work @movibeast 

Cause during the rdp I was using that site to get it. Not the CLI tool

**Comment by beetcb** [comment]
Do this : 

![add-client-secret](https://user-images.githubusercontent.com/63141491/118685438-aa9b1600-b835-11eb-9f2b-2ba6a4c4bbeb.png)

**Comment by beetcb** [comment]
Then copy the `value`, not `id` @movibeast

**Comment by movibeast** [comment]
@beetcb finally it worked! thank you very much for all of your help. I really appreciate it.

**Comment by beetcb** [comment]
I totally understand these troublesome steps because I've been there, it's really torturous and I'm glad I could help you and reduce your pain 😊

@movibeast

**Comment by movibeast** [comment]
:) really happy that you build this tool
