### ISSUE TITLE
please hlep me . 

### ISSUE THREAD

**Issue by GrapeFruitWolfs** [beetcb/ms-graph-cli#4]
I cant make my refresh_token  

> D:\Microsoft_Graph_Security_API\QuickStarts\Node\onedrive-cf-index-main>npx @beetcb/ms-graph-cli
npx: installed 36 in 7.777s
? Please select your OneDrive or SharePoint account type: Global
? Please select your deploy type (OneDrive or SharePoint): OneDrive
? Enter your client_id: 1b973335-5c01-4a1f-9002-e4125725854b
? Enter your client_secret: -aHB.9kclrsDK-_p1~252c3prxu1Xxom~I
? Enter your redirect_uri ([Default] http://localhost):
? Use your browser to visit this URL for login and authorization:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=1b973335-5c01-4a1f-9002-e4125725854b&scope=File
s.Read.All+Files.ReadWrite.All+offline_access&response_type=code&redirect_uri=http://localhost
Then enter the address you were redirected to(it's in your address bar):
 https://a.a
Get token failed!Bad Request
{
  client_id: '1b973335-5c01-4a1f-9002-e4125725854b',
  client_secret: '-aHB.9kclrsDK-_p1~252c3prxu1Xxom~I',
  redirect_uri: 'http://localhost',
  auth_endpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0',
  drive_api: 'https://graph.microsoft.com/v1.0/me/drive',
  graph_api: 'https://graph.microsoft.com/v1.0'
}

**Comment by beetcb** [comment]
https://a.a 应该是浏览器重定向的地址，或者不好理解的话，你用新版本不用自己手动填写：
```bash
npx @beetcb/ms-graph-cli@next -l CN
```
@GrapeFruitWolfs

**Comment by GrapeFruitWolfs** [comment]
十分感谢大佬  在你到指导下解决问题了，由衷感谢。

**Comment by beetcb** [comment]
小事儿 😊
