### ISSUE TITLE
Deploy type and graph permissions do not match in V0.3

### ISSUE THREAD

**Issue by ArvinZJC** [beetcb/ms-graph-cli#5]
This issue regards the deploy type selection and its corresponding permission sets observed in V0.3.

**Env**

Windows 10 (The same issue might be encountered in other platforms since I reckon it is not an OS-specific issue.)

**Example output**

```
√ Please select your OneDrive or SharePoint account type: » Global
√ Please select your deploy type (OneDrive or SharePoint): » OneDrive
√ Enter your client_id: ... test
√ Enter your client_secret: ... ****
√ Enter your redirect_uri ([Default] http://localhost:3000): ... http://localhost:3000

>>> https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=test&scope=Sites.Read.All+Sites.ReadWrite.All+offline_access...
```

**Possible reasons**

The hints/steps on the console have been defined in a JSON file `hints.json`. However, [the new logic of categorising the deploy type](https://github.com/beetcb/ms-graph-cli/blob/3807f8945e64a1a6250a23a838180cf6e06f1b8e/src/index.js#L58) seems incorrect. FYI, the value of `res` returned from `getPromptWithHints()`, as per the above example output, is as follows.

```
{
  account_type: 0,
  deploy_type: 0, // OneDrive, but in URL, permissions for SharePoint which would lead to incorrect scope.
  client_id: 'test',
  client_secret: 'test',
  redirect_uri: 'http://localhost:3000'
}
```

**Suggested fix**

pls see the pull request #6 .

**Comment by yaonyan** [comment]
Done! Plz try [v0.3.1](https://www.npmjs.com/package/@beetcb/ms-graph-cli/v/0.3.1)  
@ArvinZJC
